version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - sudo npm install -sg "gatsby-cli@1.1.25"

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - npm install -q
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - gatsby build --verbose --prefix-links

      - store_artifacts:
          path: public

workflows:
  version: 2
  build:
    jobs:
      - build
